// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asxlnxfvdrhlesvahemg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzeGxueGZ2ZHJobGVzdmFoZW1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NjUwOTEsImV4cCI6MjA2NTQ0MTA5MX0.NFl5c8LM1azZeTiCsxk2Pd_UIy8kN3FnBenACgx9n7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);